[workspace]
resolver = "2"
members = [
    "codestrain-common",
    "codestrain-server",
    "example-strain/first_choice",
    "example-strain/random",
    "example-strain/pathfinding",
    "example-strain/fill",
    "example-strain/fill-reverse",
    "example-strain/thefinnishvariant",
]
